### ISSUE TITLE
Why does alt+insert open new untitled file ?

### ISSUE THREAD

**Issue by noxasch** [kasecato/vscode-intellij-idea-keybindings#110]
Referring to this code, the description is to generate code, but what it actually do is open new untitled file.

{
                "key": "alt+insert",
                "mac": "cmd+n",
                "command": "workbench.action.files.newUntitledFile",
                "when": "!editorTextFocus",
                "intellij": "Generate code... (Getters, Setters, Constructors, hashCode/equals, toString)"
}

**Comment by pavilion** [comment]
That is because VSCode does not have a "Generate code" functionality. If you would like to do that, you will have to get the extensions that allow you to generate code and set them to Alt+Insert. 

Personally I just use CTRL + SHIFT + A and then write generate setters/getters (with Typescript Toolbox extension).

**Comment by kasecato** [comment]
@pavilion Thanks. That is correct.
@nosovsh The code generation binding just creates untitled file with focus explorer like IntelliJ.

**Comment by nosovsh** [comment]
Wrong user mention :)

**Comment by nosovsh** [comment]
@noxasch

**Comment by kasecato** [comment]
Closed by #271
