### ISSUE TITLE
Comment/uncomment with line comment 

### ISSUE THREAD

**Issue by antonwnk** [kasecato/vscode-intellij-idea-keybindings#87]
The caret does not jump to the next line after the commenting is done

**Comment by spik3s** [comment]
This cannot  be achieved at the moment without additional extensions since VS Code does not currently allow chaining commands.  You should try [macros](https://marketplace.visualstudio.com/items?itemName=geddski.macros) or [multicommand](https://marketplace.visualstudio.com/items?itemName=ryuta46.multi-command).

@Microsoft/vscode#871

**Comment by kasecato** [comment]
Closed due to duplicate with #233
